# Required version
version: 2

# OS and Python setup
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Install dependencies and package
python:
  install:
    - method: pip
      path: .
    - method: pip
      name: trading212-connector  # Explicitly install the package

# Use Sphinx to build docs
sphinx:
  configuration: docs/source/conf.py

# Enable additional Sphinx extensions
formats:
  - html
  - pdf
  - epub
